configMapGenerator:
- files:
  - application.yml
  name: 82022583-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
namespace: "82022583"
images:
- name: ceappacr.azurecr.io/82022583
  newTag: "202410071120"
